name: Urbansol_App
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
    sdk: ">=2.19.4 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    share: ^2.0.1
    english_words: ^4.0.0
    provider: ^6.0.0
    pdf: ^3.10.4
    printing: ^5.11.0
    open_file: ^3.3.2
    path_provider: ^2.1.1
    url_launcher: ^6.2.1
    intl: ^0.18.1

dev_dependencies:
    flutter_launcher_icons: ^0.13.1

    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - fonts/
        - imgs/
